SlotWise.Web/Controllers/ServiceController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SlotWise.Web.Core;
using SlotWise.Web.Core.Pagination;
using SlotWise.Web.DTOs;
using SlotWise.Web.Services.Abstractions;
using SlotWise.Web.Services.Implementations;

namespace SlotWise.Web.Controllers
{
    public class ServiceController : Controller
    {
        private readonly IServiceService _serviceService;
        private readonly ISpecialistService _specialistService;
        private readonly INotyfService _notyfService;

        public ServiceController(IServiceService serviceService,ISpecialistService specialistService, INotyfService notyfService)
        {
            _serviceService = serviceService;
            _specialistService = specialistService;
            _notyfService = notyfService;

        }
        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] PaginationRequest request)
        {
            try
            {
                Response<PaginationResponse<ServiceDTO>> response = await _serviceService.GetPaginatedListAsync(request);

                if (!response.IsSuccess)
                {
                    
                    ViewBag.ErrorMessage = response.Message;
                    return View(new PaginationResponse<ServiceDTO>());
                }
                

                return View(response.Result);
            }
            catch (Exception ex)
            {
                // Captura cualquier excepción no manejada
                ViewBag.ErrorMessage = ex.Message;
                return View(new PaginationResponse<ServiceDTO>());
            }
        }
        //[HttpGet]
        //public IActionResult Create()
        //{
        //    return View();
        //}

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            // Obtenemos la lista de especialistas desde el servicio
            Response<List<SpecialistDTO>> specialistsResponse = await _specialistService.GetListAsync();

            // Si todo va bien, llenamos el ViewBag para el <select>
            if (specialistsResponse.IsSuccess)
            {
                ViewBag.Specialists = new SelectList(
                    specialistsResponse.Result, // Lista de especialistas
                    "Id",                       // Valor que se guarda (SpecialistId)
                    "FirstName"                 // Lo que se muestra en pantalla (puedes usar "FullName" si existe)
                );
            }
            else
            {
                // Si algo falla, al menos enviamos una lista vacía para evitar errores
                ViewBag.Specialists = new SelectList(new List<SpecialistDTO>(), "Id", "FirstName");
            }

            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Create([FromForm] ServiceDTO dto)
        {


            if (!ModelState.IsValid)
            {
                _notyfService.Error("Debe ajustar los errores de validación");
                return View(dto);
            }

            Response<ServiceDTO> response = await _serviceService.CreateAsync(dto);

            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
                return View(dto);
            }

            _notyfService.Success(response.Message);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Edit([FromRoute] Guid id)
        {
            Response<ServiceDTO> response = await _serviceService.GetOneAsync(id);

            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
                return RedirectToAction(nameof(Index));
            }
            var specialists = await _specialistService.GetListAsync();
            ViewBag.Specialists = specialists.Result?
             .Select(s => new SelectListItem
              {
                  Value = s.Id.ToString(),
                  Text = s.FirstName + " " + s.LastName
              })
        .ToList();
            return View(response.Result);
        }

        

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] ServiceDTO dto)
        {
            if (!ModelState.IsValid)
            {
                _notyfService.Error("Debe ajustar los errores de validación");
                return View(dto);
            }

            Response<ServiceDTO> response = await _serviceService.EditAsync(dto);

            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
                

                Response<List<SpecialistDTO>> specialists = await _specialistService.GetListAsync();
                ViewBag.Specialists = specialists.Result;
                return View(dto);
            }
            
            _notyfService.Success(response.Message);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] Guid id)
        {
            Response<object> response = await _serviceService.DeleteAsync(id);

            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
            }
            else
            {
                _notyfService.Success(response.Message);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Toggle([FromForm] ToggleServiceStatusDTO dto)
        {
            Response<object> response = await _serviceService.ToggleAsync(dto);

            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
            }
            else
            {
                _notyfService.Success(response.Message);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

SlotWise.Web/Controllers/SpecialistController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using SlotWise.Web.Core;
using SlotWise.Web.Core.Pagination;
using SlotWise.Web.DTOs;
using SlotWise.Web.Services.Abstractions;
using SlotWise.Web.Services.Implementations;

namespace SlotWise.Web.Controllers
{
    public class SpecialistController : Controller
    {
        private readonly ISpecialistService _specialistService;
        private readonly INotyfService _notyfService;

        public SpecialistController(ISpecialistService specialistService, INotyfService notyfService)
        {
            _specialistService = specialistService;
            _notyfService = notyfService;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] PaginationRequest request)
        {
            try
            {
                var response = await _specialistService.GetPaginatedListAsync(request);

                if (!response.IsSuccess)
                {
                    // Mostrar el mensaje de error en la vista
                    ViewBag.ErrorMessage = response.Message;
                    return View(new PaginationResponse<SpecialistDTO>());
                }

                return View(response.Result);
            }
            catch (Exception ex)
            {
                // Captura cualquier excepción no manejada
                ViewBag.ErrorMessage = ex.Message;
                return View(new PaginationResponse<SpecialistDTO>());
            }
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] SpecialistDTO dto)
        {
            if (!ModelState.IsValid)
            {
                _notyfService.Error("Debe ajustar los errores de validación");
                return View(dto);
            }

            Response<SpecialistDTO> response = await _specialistService.CreateAsync(dto);

            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
                return View(dto);
            }

            _notyfService.Success(response.Message);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Edit([FromRoute] Guid id)
        {
            Response<SpecialistDTO> response = await _specialistService.GetOneAsync(id);

            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
                return RedirectToAction(nameof(Index));
            }

            return View(response.Result);
        }
        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] SpecialistDTO dto)
        {
            if (!ModelState.IsValid)
            {
                _notyfService.Error("Debe ajustar los errores de validación");
                return View(dto);
            }

            Response<SpecialistDTO> response = await _specialistService.EditAsync(dto);

            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
                return View(dto);
            }

            _notyfService.Success(response.Message);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] Guid id)
        {
            Response<object> response = await _specialistService.DeleteAsync(id);

            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
            }
            else
            {
                _notyfService.Success(response.Message);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Toggle([FromForm] ToggleSpecialistStatusDTO dto)
        {
            Response<object> response = await _specialistService.ToggleAsync(dto);

            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
            }
            else
            {
                _notyfService.Success(response.Message);
            }

            return RedirectToAction(nameof(Index));
        }
        /*
         * Este fragmento sirve para hacer Debug a lo que trae GetPaginatedListAsync se debe ir al edponid /Specialist/TestData para visualizar el error 
         * 
        public async Task<IActionResult> TestData()
        {
            try
            {
                // Probar GetListAsync
                var serviceResult = await _specialistService.GetListAsync();
                ViewBag.ServiceSuccess = serviceResult.IsSuccess;
                ViewBag.ServiceMessage = serviceResult.Message;
                ViewBag.ServiceData = serviceResult.Result;
                ViewBag.ServiceDataCount = serviceResult.Result?.Count ?? 0;

                // Probar paginación
                var paginationResult = await _specialistService.GetPaginatedListAsync(new PaginationRequest());
                ViewBag.PaginationSuccess = paginationResult.IsSuccess;
                ViewBag.PaginationMessage = paginationResult.Message;
                ViewBag.PaginationData = paginationResult.Result;
                ViewBag.PaginationDataCount = paginationResult.Result?.List?.Count ?? 0;

                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }*/
    }
}

SlotWise.Web/Controllers/UserController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using SlotWise.Web.Core;
using SlotWise.Web.Core.Pagination;
using SlotWise.Web.DTOs;
using SlotWise.Web.Services.Abstractions;

namespace SlotWise.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly INotyfService _notyfService;
        public UserController(IUserService userService, INotyfService notyfService)
        {
            _userService = userService;
            _notyfService = notyfService;
        }
        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] PaginationRequest request)
        {
            try
            {
                Response<PaginationResponse<UserDTO>> response = await _userService.GetPaginatedListAsync(request);
                if (!response.IsSuccess)
                {
                    // Mostrar el mensaje de error en la vista
                    ViewBag.ErrorMessage = response.Message;
                    return View(new PaginationResponse<UserDTO>());
                }
                return View(response.Result);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View(new PaginationResponse<UserDTO>());
            }
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] UserDTO dto)
        {
            if (!ModelState.IsValid)
            {
                _notyfService.Error("Debe ajustar los errores de validación");
                return View(dto);
            }
            Response<UserDTO> response = await _userService.CreateAsync(dto);
            if (!response.IsSuccess)
            {
                _notyfService.Error(response.Message);
                return View(dto);
            }
            _notyfService.Success(response.Message);
            return RedirectToAction(nameof(Index));
        }

    }
}

SlotWise.Web/Views/Shared/_Footer.cshtml
<!-- ======= Footer ======= -->
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>PrivateBlog</span></strong>. All Rights Reserved
    </div>
</footer><!-- End Footer -->

SlotWise.Web/Views/Shared/_Header.cshtml
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="index.html" class="logo d-flex align-items-center">
            <img src="~/assets/img/logo.png" alt="">
            <span class="d-none d-lg-block">SlotWise</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">


            <li class="nav-item dropdown pe-3">

                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                    <img src="" alt="Profile" class="rounded-circle">
                    <span class="d-none d-md-block dropdown-toggle ps-2">Admin</span>
                </a><!-- End Profile Iamge Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>Administrador</h6>
                        <span>Administrador</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                            <i class="bi bi-person"></i>
                            <span>Mi perfil</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                            <i class="bi bi-gear"></i>
                            <span>Configuracion</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                            <i class="bi bi-question-circle"></i>
                            <span>Necesitas ayuda?</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Salir</span>
                        </a>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

SlotWise.Web/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] - SlotWise</title>

    <meta content="" name="description">
    <meta content="" name="keywords">

    @await Html.PartialAsync("_Styles");

    <!-- =======================================================
    * Template Name: NiceAdmin
    * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
    * Updated: Mar 17 2024 with Bootstrap v5.3.3
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    @await Html.PartialAsync("_Header")

    @await Html.PartialAsync("_Sidebar")
    <main id="main" class="main">

        @RenderBody()

    </main>

    @await Html.PartialAsync("_Footer")

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    @await Html.PartialAsync("_Scripts")

    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("Notyf")


</body>

</html>

SlotWise.Web/Views/Shared/_Scripts.cshtml
<!-- Vendor JS Files -->
<script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
<script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/assets/vendor/chart.js/chart.umd.js"></script>
<script src="~/assets/vendor/echarts/echarts.min.js"></script>
<script src="~/assets/vendor/quill/quill.min.js"></script>
<script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
<script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
<script src="~/assets/vendor/php-email-form/validate.js"></script>

<!-- Template Main JS File -->
<script src="~/assets/js/main.js"></script>

<script src="~/lib/jquery/dist/jquery.min.js"></script>

<script src="~/lib/sweetalert2/sweetalert2@11.js"></script>

SlotWise.Web/Views/Shared/_Sidebar.cshtml
<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link " href="index.html">
                <i class="bi bi-grid"></i>
                <span>Inicio</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="Specialist" asp-action="Index">
                <i class="bi bi-person-badge"></i> <span>Especialistas</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="User" asp-action="Index">
                <i class="bi bi-person"></i> <span>Usuario</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="Service" asp-action="Index">
                <i class="bi bi-clipboard-check"></i> <span>Servicios</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="Booking" asp-action="Index">
                <i class="bi bi-calendar-plus"></i> <span>Reserva</span>
            </a>
        </li>

        
        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-menu-button-wide"></i><span>Components</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="components-alerts.html">
                        <i class="bi bi-circle"></i><span>Alerts</span>
                    </a>
                </li>
                <li>
                    <a href="components-accordion.html">
                        <i class="bi bi-circle"></i><span>Accordion</span>
                    </a>
                </li>
            </ul>
        </li> 

    </ul>

</aside>

SlotWise.Web/Views/Shared/_Styles.cshtml
<!-- Favicons -->
<link href="~/assets/img/favicon.png" rel="icon">
<link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

<!-- Google Fonts -->
<link href="https://fonts.gstatic.com" rel="preconnect">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

<!-- Vendor CSS Files -->
<link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
<link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
<link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
<link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
<link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
<link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

<!-- Template Main CSS File -->
<link href="~/assets/css/style.css" rel="stylesheet">